### ISSUE TITLE
How to compile it？

### ISSUE THREAD

**Issue by 408550969** [Goingqs/TensorRT-SSD#1]
Thank you very much for sharing the code.May I ask how to compile it?
I can run 40FPS on other versions of TensorRT-SSD（VGG-16,PASCAL VOC,batch_size=1,gtx1070,FP32）
As far as I know, 1080ti is not much faster than 1070. In addition to the influence of the base network,What other ways do you use to run so fast in high resolution?

**Comment by lucheng07082221** [comment]
@Goingqs wher is the caffemodel and deployfile?

**Comment by 408550969** [comment]
There are some mistakes when I compile:
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:688：undefined reference to‘cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:693：undefined reference to‘cv::_OutputArray::_OutputArray(cv::Mat&)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:693：undefined reference to‘cv::_InputArray::_InputArray(cv::Mat const&)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:693：undefined reference to‘cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:695：undefined reference to‘cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:697：undefined reference to‘cv::_OutputArray::_OutputArray(cv::Mat&)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:697：undefined reference to‘cv::_InputArray::_InputArray(cv::Mat const&)’
/home/cll/TensorRT-4.0.1.6/targets/x86_64-linux-gnu/samples/ssd/sampleDetect.cpp:697：undefined reference to‘cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)’
/usr/include/opencv2/core/mat.hpp:278：undefined reference to‘cv::fastFree(void*)’
/usr/include/opencv2/core/mat.hpp:367：undefined reference to‘cv::Mat::deallocate()’
collect2: error: ld returned 1 exit status
../Makefile.config:153: recipe for target '../../bin/sample_ssd_debug' failed
make: *** [../../bin/sample_ssd_debug] Error 1

**Comment by 408550969** [comment]
Do you know how to compile it？
@lucheng07082221  @Goingqs

**Comment by lucheng07082221** [comment]
@408550969 你可以加我qq：408658624 我告诉你
